<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Answer extends Model
{
//    public $timestamps = true;

//    public function getDateFormat()
//    {
//        return time(); // TODO: Change the autogenerated stub
//    }

    public function add(){
        if (!user_ins()->isLogined())
            return ['status' => 0, 'msg' => 'login required'];

        if (!rq('question_id'))
            return ['status' => 0, 'msg' => 'question required'];

        $question = question_ins()->find(rq('question_id'));
        if(!$question) return ['status' => 0, 'msg' => 'question not exists'];
        $this->content = rq('content');
        $this->question_id = rq('question_id');
        $this->user_id = session('user_id');
        return $this->save() ? ['status' => 1, 'id' => $this->id] : ['status' => 0, 'msg' => 'insert failed'];
    }


    public function vote()
    {
        if (!user_ins()->isLogined())
            return ['status' => 0, 'msg' => 'login required'];
        if (!rq('id') || !rq('vote'))
            return ['status' => 0, 'msg' => 'id and vote required'];

        $answer = $this->find(rq('id'));
        if (!$answer) return ['status' => 0, 'msg' => 'answer not exists'];
        $vote = rq('vote') <= 1 ? 1 : 2;
        $answer->users()
            ->newPivotStatement()
            ->where('user_id', session('user_id'))
            ->where('answer_id', rq('id'))
            ->delete();
//        if($vote_exist)
//            $vote_exist->delete();

        $answer->users()->attach(session('user_id'), ['vote' => $vote]);
        return ['status' => 1];
    }

    public function users()
    {
        return $this
            ->belongsToMany('App\User')
            ->withPivot('vote')
            ->withTimestamps();
    }
}
